create table org_unit (
    id int8 generated by default as identity,
    manager_ref varchar(255), name varchar(255),
    organisation_unit_id varchar(255),
    parent_ref varchar(255),
    resource_id varchar(255),
    short_name varchar(255),
    primary key (id));

create table org_unit_children_ref (
    org_unit_id int8 not null,
    children_ref varchar(255));

alter table if exists org_unit_children_ref add constraint FKql36nq6uathi09wv7oj07v2x2 foreign key (org_unit_id) references org_unit;
